### ISSUE TITLE
API for interactivity

### ISSUE THREAD

**Issue by rochoa** [CartoDB/carto-vl#61]
The goal of this issue is to define and implement the carto-vl interactivity system.

We need to provide an api to define the ways in which the user interacts with the map.

 - **click**: The user clicks/touches a location on the map.
 - **move**: The user moves the mouse to a location on the map

As described in the [draft](https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w/edit#heading=h.p3rhg6rfxc) we need to provide a way to set up event listeners for those events for every layer displayed on the map.

We must provide a way to know if there is some data in the location where the user interacted.

## Events
- `featureClick`: when you click on a feature.
- `featureClickOut`: when you click out of a feature you clicked in.
- `featureEnter`: when your pointer enters a feature.
- `featureHover`: when you are moving inside a feature you have entered.
- `featureLeave`: when your pointer leaves a feature you entered before.

### Subscribe to an event

```js
const interactivity = new carto.Interactivity([layer]);
interactivity.on('featureClick', event => {});
interactivity.on('featureClickOut', event => {});
interactivity.on('featureEnter', event => {});
interactivity.on('featureHover', event => {});
interactivity.on('featureLeave', event => {});
```

```js
const interactivity = new carto.Interactivity([cities, countries]);

interactivity.on('featureClick', event => {
    feature = event.features[0];
    if (feature.layer == 'countries') {
        popupCountries(feature);
    } else {
       popupCities(feature);
    }
});

interactivity.on('featureClickOut', event => {
    popupDisable();    
});
```

### Event Callback

The callback is a function that receives a single `FeatureEvent` parameter
A FeatureEvent has the following fields:

- features. Array of features located at the interaction location, each one will have:
    - properties: Multiple data fields 
    - id (featureID)
    - layerId (string, MGL)
- position (in pixels)
- coordinates (long lat)

## TODO
- [x] Define public api to listen to click events.
- [x] Define public api to listen to hover events.
- [x] Define the FeatureEvent object taking into account all the requisites listed in this issue.
- [x] Define a way to change the feature style (better within the callback)
- [x] Create unit tests for the public API
- [x] Create an example: (console.log feature data on feature-click/hover)
- [x] Define integration tests for this use-case
- [x] Add public documentation (jsdoc)
- [x] Implement click event
- [x] Implement hover event
- [x] Implement intersection tests: points, polygons and lines
- [x] Implement variables

## TODO (issues)
https://github.com/CartoDB/renderer-prototype/issues/197

**Comment by IagoLast** [comment]
I suggest to use [this](https://github.com/developit/mitt) as event emitter

**Comment by rochoa** [comment]
Event naming follows camelCase.
In each event you should get:
 - The geometry.
 - All its properties.
 - A way to interact with the style. We don't need the implementation of this yet.
 - Mouse position: long, lat and potential pixels.

## Events:
1. `featureClick`: when you click on a feature.
1. `featureClickOut`: when you click out of a feature you clicked in.
1. `featureEnter`: when your pointer enters a feature.
1. `featureHover`: when you are moving inside a feature you have entered.
1. `featureLeave`: when your pointer leaves a feature you entered before.

Interactivity could be **per layer** or per map. We need to evaluate what of the two alternatives is better at implementation and API level.

Note: Don't forget about _dragging_.

[Mapbox GL events reference](https://www.mapbox.com/mapbox-gl-js/api/#map#on).

**Comment by Jesus89** [comment]
Tasks

- Create carto.Interactivity() object API (+docs +tests)
  - Initialize map events
  - Add `on` function
  - Add `off` function
- Create Feature object 
- Add `featureClick`, `featureClickOut`, `featureEnter`, `featureLeave`, `featureHover`

---

- Decouple dataframes / webgl
- Add `detectPoint` in RenderLayer (+tests)
- Add `detectPolygon` in RenderLayer (+tests)
- Add `detectLine` in RenderLayer (+tests)

---

- Add detection with radius (threshold)
- Add detection for heatmaps

---

- Add Style to Feature object (+docs + tests)
  - Get “properties”
  - Get / setStyle(styleSpec)
  - blendToStyle(styleSpec)
  - “isAgg()”
