### ISSUE TITLE
[EPIC] - Restructure documentation

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/carto-vl#950]
# Restructure Tech. Doc Issues:

> NOTE: This issue's description is being frequently updated. Have a quick look when you enter it after some time...

## 1. Overview
  * [ ] Update "Overview" using README.md introduction: https://github.com/CartoDB/carto-vl/issues/965.

## 2. Guides 
  * [x] Update "1. Getting Started": https://github.com/CartoDB/carto-vl/issues/966
  * [x] Add "2. Using data in your visualization with Sources": https://github.com/CartoDB/carto-vl/issues/967
  * [x] Add "3. Styling Properties using expressions": https://github.com/CartoDB/carto-vl/issues/969
  * [x] Add "4. Data Driven Visualizations (I and II)" https://github.com/CartoDB/carto-vl/issues/970
  * [x] Add "5. Legends and Widgets". 
  * [x] Add "6. Aggregating Data" https://github.com/CartoDB/carto-vl/issues/971
  * [x] Add "7. Zoom-based Styling" https://github.com/CartoDB/carto-vl/issues/973
  * [x] Add "8. Animated visualizations" https://github.com/CartoDB/carto-vl/issues/974
  * [x] Add "9. Interactivity and events" https://github.com/CartoDB/carto-vl/issues/975
  * [ ] ~~Add "10. Adding labels" (to be defined)~~ https://github.com/CartoDB/carto-vl/issues/704
  * [ ] ~~Add "11. Advanced tips"~~ https://github.com/CartoDB/carto-vl/issues/976
  * [x] Remove these guides (moved to `guides/deprecated` subfolder): 
    * "Introduction to Expressions"
    * "Introduction to Interpolation"
    * "Introduction to Styling"
    * "Introduction to Animation"
    * "Introduction to Interactivity"
    * "Introduction to Image Files"
    * "The Basics of Syntax"

More info in this [Spreadsheet](https://docs.google.com/spreadsheets/d/1M5sKwIkkAD_DOp2zbM1WhST3waHN2BY2ICdcW4J-ztA/edit#gid=0)

## 3. Reference [PR]
* [x] Check and refactor https://github.com/CartoDB/carto-vl/issues/977 by @elenatorro and @VictorVelarde 

## 4. Examples [WIP] 
* [ ] https://github.com/CartoDB/carto-vl/issues/978 by @makella [working PR: https://github.com/CartoDB/carto-vl/pull/987]

## 5. Glossary
~~* [x] Add Glossary / entries: https://github.com/CartoDB/carto-vl/issues/979~~ --> help center

## 6. Improvements
  * [x] Fix highlight in code on enter guides page
  * [x] String API fix - use String API first (PR - reference)
  * [x] Make documentation available for different versions @elenatorro 
 https://github.com/CartoDB/carto-vl/issues/898

## 7. Conventions

* **CARTO VL** (remember to use it always like this!). See [this doc](https://docs.google.com/document/d/1eCdg9_ah8bpJcIclSbT6L_ELAAqFbV7K7Ws2cTMZup8/edit#)

* Use **Second Voice** when explaining the examples: 
    * Good: "The first thing **you** need to do is authenticate the client"
    * Wrong:  "The first thing **we** need to do is authenticate the client"

* **Guide names**: we should keep the number as a preffix and use a clear name for the main .md file, eg. `01-getting-started.md`. And we should use `step-1.html`, `step-2-html` in the corresponding examples/guides

* Adding **comments to examples**: we should follow the same naming when creating examples, and name them as we do in the `Getting Started` guide. More info in the issue: https://github.com/CartoDB/carto-vl/issues/966

* To embed examples in the guides (https://github.com/CartoDB/carto-vl/issues/980) use:
```html
<div class="example-map">
    <iframe 
        id="getting-started-basic-styling-map"
        src="/developers/carto-vl/examples/maps/guides/getting-started/basicStyling.html" 
        width="100%"
        height="500" 
        frameBorder="0">
    </iframe>
</div>
```

* Notice how in the previous example, **/developers/** was used instead of **https://carto.com/developers/**. That way we can be more flexible and make relative links in the tech doc for different environments (eg. dev center at staging).

* To get a working map, as a starting point in your guide, you can use this: `[basemap](/developers/carto-vl/examples/maps/guides/getting-started/step-1.html)`.

* The **/maps/** fragment in the urls is going to be probably removed, but it is still required at dev-center

* Use `viz`, `source` and `layer` names for consistency (only name them differently if we have more than one source/viz/layer)

**Comment by VictorVelarde** [comment]
After my meeting with @elenatorro I'd like to add some ideas:

**GUIDES**
- Start with the 'Final Result', an embedded working map.
- Add Level (basic, intermediate...) and pre-requisites (eg. for 'Getting Started' --> basic HTML & JS? goto X course if not...?)
- Use a 'step-by-step' approach towards that result (not very broad guides, enumerating a lot of options, but very goal-oriented)
- Rename 'Visualizations' guide, to include 'Maps' in the title

**EXAMPLES**
- Keep same general structure as in guides (add 'sources' category)
- Add 'Search in' examples
- Take some 'Advanced examples' and turn them into a **Showcase**, somewhere out of this section, for people evaluating the library

**REFERENCE**
- 👍 to use a hierarchy, using each main "parent node" to add a little paragraph on the topic. Eg. `Expressions > Classifications`... Classifications are [....] and then each method function

**Comment by elenatorro** [comment]
I have updated the issue description with the list of ideas @VictorVelarde mentions above. 

I have a question about the **reference** section, do you mean to have some like of breadcrumbs in the docs?

**Comment by VictorVelarde** [comment]
> I have updated the issue description with the list of ideas @VictorVelarde mentions above.
> 
> I have a question about the **reference** section, do you mean to have some like of breadcrumbs in the docs?

No, it was just a way to make an emphasis on the 'tree' structure

**Comment by makella** [comment]
just something i want to note so i don't forget... similar to how we can see syntax in the string vs. js api in the reference, i wonder if there is a way we can do the same for the examples since that was a big request after the hackathon, more js api examples.

**Comment by elenatorro** [comment]
after talking with @makella & @davidmanzanares, we could do a PoC like this page: https://www.data-to-viz.com

**Comment by makella** [comment]
@elenatorro @davidmanzanares and I had a marathon meeting (way to go!!) we reorganized the content and structure in the guides section above. the examples and reference still need to be organized w/in the higher level context of the guides which we will do next.

**Comment by makella** [comment]
To update here:

Now that we have the Guides submitted: 
- I will be doing a general copy-edit process
- Look through the maps that we have in each one with the goals of: 
  - reusing for the examples section (where appropriate), 
  - for more robust examples inside of Guides that link directly to the examples, those will be put in a separate folder (for example Data Driven Vis maps) 
  - do any cartographic adjustments
- Some house cleaning 
  - Guides order
  - Guides title
  - css for small things like the font (i.e. Montserrat, Open Sans > Roboto)
